outline
ultralight-beam/UBIPs pull request #1
Opened 2019-05-22 22:46 UTC by GregTheGreek

2019-05-22 22:47 UTC, decanus commented on README.md
> +The UB project's development process is design-driven. Significant changes to the language, libraries, or tools must be first discussed, and sometimes formally documented, before they can be implemen
```suggestion
The UB project's development process is design-driven. Significant changes to the protocol, libraries, or tools must be first discussed, and sometimes formally documented, before they can be implemented.
```

2019-05-22 22:51 UTC, tueric commented on README.md
> +  - decline proposal.
Formatting not consistent from point 2.

2019-05-22 22:55 UTC, decanus requested changes

2019-05-22 22:55 UTC, decanus commented on README.md
> +## Introduction
```suggestion

## Introduction
```

2019-05-22 22:59 UTC, GregTheGreek commented on README.md
> +  - decline proposal.
fixed

2019-05-22 22:59 UTC, decanus submitted a review, later dismissed

2019-05-22 22:59 UTC, decanus commented on README.md
> +3. The proposal author writes a [design doc](#design-documents) to work out details of the proposed
Referencing a non existant section

2019-05-22 23:01 UTC, decanus requested changes

2019-05-22 23:01 UTC, decanus commented on README.md
> +1. The proposal author [creates a brief issue](https://golang.org/issue/new) describing the proposal.\
```suggestion
The proposal author [creates a brief issue](https://github.com/ultralight-beam/UBIPs/issues/new) describing the proposal.\
```

2019-05-22 23:06 UTC, ec2 submitted a review, later dismissed

2019-05-22 23:06 UTC, tueric commented on README.md
> +    - Accept proposal or
add a comma. otherwise, LGTM

2019-05-22 23:06 UTC, GregTheGreek commented on README.md
> +    - Accept proposal or
suggest it plz

2019-05-22 23:09 UTC, tueric commented on README.md
> +    - Accept proposal or
```suggestion
    - Accept proposal, or
```

2019-05-22 23:11 UTC, decanus submitted a review, later dismissed

2019-05-22 23:28 UTC, decanus approved these changes

2019-05-23 00:53 UTC, wemeetagain approved these changes

2019-05-23 05:21 UTC, decanus approved these changes

2019-05-23 17:27 UTC, merged